apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  labels:
    account: demo
  name: demo
spec:
  assumeRoleChain:
    - roleARN: arn:aws:iam::00000002:role/Crossplane
  credentials:
    source: IRSA
